const aiml=[
    {
        id:1,
        name:"tensorflow",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/tensorflow/tensorflow-original.svg"
    },
    {
        id:2,
        name:"pytorch",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/pytorch/pytorch-original.svg"
    },
    {
        id:3,
        name:"keras",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/keras/keras-original.svg"
    },
    {
        id:4,
        name:"scikit-learn",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/scikit-learn/scikit-learn-original.svg"
    },
    {
        id:5,
        name:"fastai",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/fastai/fastai-original.svg"
    },
    {
        id:6,
        name:"pandas",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/pandas/pandas-original.svg"
    },
    {
        id:7,
        name:"numpy",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/numpy/numpy-original.svg"
    },
    {
        id:8,
        name:"openai",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/openai/openai-original.svg"
    },
    {
        id:9,
        name:"dialogflow",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/dialogflow/dialogflow-original.svg"
    },
      
]
export default aiml;    