const database=[
    {
        id:1,
        name:"mysql",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
    },
    {
        id:2,
        name:"mongodb",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
    },
    {
        id:3,
        name:"postgresql",  
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg"
    },
    {
        id:4,
        name:"redis",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original-wordmark.svg"
    },
    {
        id:5,
        name:"sqlite",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/sqlite/sqlite-original-wordmark.svg"
    },
    {
        id:6,
        name:"elasticsearch",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/elasticsearch/elasticsearch-original-wordmark.svg"
    },
    {
        id:7,
        name:"couchdb",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/couchdb/couchdb-original-wordmark.svg"
    },
    {
        id:8,
        name:"cassandra",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/cassandra/cassandra-original-wordmark.svg"
    },
    {
        id:9,
        name:"firebase",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/firebase/firebase-plain-wordmark.svg"
    },
    {
        id:10,
        name:"oracle",
        icon:"https://raw.githubusercontent.com/devicons/devicon/master/icons/oracle/oracle-original.svg"
    }
]
export default database;